from fastapi import APIRouter
from app.api.v1.endpoints import (
    auth, users, products, purchase, billing,
    warehouse, accounting, gst, reports, bank, security, settings,
    price_history, dpdp, config_admin,
)

api_router = APIRouter(prefix="/api/v1")
api_router.include_router(auth.router)
api_router.include_router(users.router)
api_router.include_router(products.cat_router)
api_router.include_router(products.router)
api_router.include_router(price_history.price_history_router)
api_router.include_router(purchase.vendor_router)
api_router.include_router(purchase.purchase_router)
api_router.include_router(purchase.payment_router)
api_router.include_router(billing.customer_router)
api_router.include_router(billing.invoice_router)
api_router.include_router(billing.receipt_router)
api_router.include_router(warehouse.warehouse_router)
api_router.include_router(warehouse.transfer_router)
api_router.include_router(warehouse.adjustment_router)
api_router.include_router(warehouse.writeoff_router)
api_router.include_router(warehouse.opening_router)
api_router.include_router(accounting.cheque_router)
api_router.include_router(accounting.cash_router)
api_router.include_router(accounting.expense_router)
api_router.include_router(accounting.tds_router)
api_router.include_router(accounting.ageing_router)
api_router.include_router(accounting.journal_router)
api_router.include_router(accounting.vendor_due_router)
api_router.include_router(gst.transporter_router)
api_router.include_router(gst.vehicle_router)
api_router.include_router(gst.einvoice_router)
api_router.include_router(gst.eway_router)
api_router.include_router(gst.gstr1_router)
api_router.include_router(gst.gstr2b_router)
api_router.include_router(gst.gstr3b_router)
api_router.include_router(reports.dashboard_router)
api_router.include_router(reports.reports_router)
api_router.include_router(bank.bank_stmt_router)
api_router.include_router(bank.bank_recon_router)
api_router.include_router(bank.notification_router)
api_router.include_router(bank.backup_router)
api_router.include_router(bank.scheduled_router)
api_router.include_router(security.users_router)
api_router.include_router(security.sessions_router)
api_router.include_router(security.activity_router)
api_router.include_router(security.login_history_router)
api_router.include_router(security.twofa_router)

api_router.include_router(settings.router)
api_router.include_router(dpdp.router)
api_router.include_router(config_admin.router)
